name: Node CI

on: [push]

jobs:
  seed:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Yarn
      uses: CultureHQ/actions-yarn@v1.0.1
    - name: Install Dependencies
      run:
        yarn
    - name: Prepare Database
      run:
        yarn db:init
      env:
        NODE_ENV: test
    - name: Seed Database
      run:
        yarn sequelize db:seed:all
      env:
        NODE_ENV: test
